version: "3"

services:
  react-app:
    container_name: react_container
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - node-api
    networks:
      - mern-network
    stdin_open: true
    tty: true

  node-api:
    container_name: node_container
    build: ./backend
    ports:
      - "8081:8081"
    restart: always
    networks:
      - mern-network
    depends_on:
      - mongo-db

  mongo-db:
    container_name: mongo_container
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge